apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Chart.Name }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - patch
      - create
